### PR TITLE
Ability to use .length outside of []

### PR DESCRIPTION
**Pull request by SergeyNikolaev**
Hi Galbar, my users would like to use .length operator outside of brackets in order to get length of a JSON array or string value length. Like they can do at https://jsonpath.com.
So, I've made a simple update to your lib, it should work fine in case there is nothing with key 'length' at these array level.
What do you think about that?

### CODE REVIEW

**Comment by Galbar** [comment]
Hi @SergeyNikolaev ! Thanks for the contribution. Looks useful!

Could you please add unit tests that demonstrate the changes? I'm thinking a few scenarios to test:
* `length` as an intermediate object: `$.some.path.length.begin`
* Object has field `length`: `$.some.path.object.length`
* String length: `$.some.path.string.length`
* Array length`$.some.path.array.length`
* Length of each array inside an array of arrays: `$.some.path.to.array_of_arrays[*].length`
* Length of each array inside an array of strings: `$.some.path.to.array_of_strings[*].length`

Also, could you update the specification of the language in the README.md file?

Again, thanks for the contribution! :+1:

**Comment by SergeyNikolaev** [comment]
Sure, thanks 👍

**Comment by SergeyNikolaev** [comment]
Hi @Galbar I have made an updates with tests and README.md file for the new functionality and also added two new cases with length of each array inside an array of arrays, and length of each string inside an array of strings. 

And also I have found this feature with length of each array inside an array of arrays is not very useful, I think it would be better to return an actual top level length of an array (or strings), as far as I can tell for my users, but, maybe I'm wrong, what do you think?

Do you have any suggestions?

**Comment by Galbar** [comment]
Hi @SergeyNikolaev, thanks!

I haven't had time to have a look at it. I'll review it when I have time (hopefully soon).

Sorry for the delay

**Comment by SergeyNikolaev** [comment]
up

**Comment by Galbar** [comment]
Hey @SergeyNikolaev,

I finally had some time to check this. Looks good. I'm merging it :)

**Comment by SergeyNikolaev** [comment]
@Galbar awesome! Thanks.

**Pull request merged**
